"""Background thumbnail generator with disk cache for instant reloads."""
import hashlib
import json
import os
from collections import deque, OrderedDict
from pathlib import Path
from PySide6.QtCore import QThread, Signal, QMutex, QMutexLocker
from PySide6.QtGui import QPixmap, QImage

from doxyedit.imaging import open_for_thumb, pil_to_qpixmap

THUMB_SIZE = 160
CACHE_DIR_NAME = ".doxyedit_cache"

# Fast cache mode: store uncompressed BMP instead of PNG.
# Reads/writes ~3-5x faster but uses ~10x more disk space per thumbnail.
# Toggled via QSettings key "fast_cache" (0 or 1).
_FAST_FMT = "BMP"
_FAST_EXT = ".bmp"
_STD_FMT  = "PNG"
_STD_EXT  = ".png"


def _cache_fmt() -> tuple[str, str]:
    """Return (format, ext) based on fast_cache setting."""
    from PySide6.QtCore import QSettings
    fast = QSettings("DoxyEdit", "DoxyEdit").value("fast_cache", 0, type=int)
    return (_FAST_FMT, _FAST_EXT) if fast else (_STD_FMT, _STD_EXT)


def _cache_key(path: str, size: int) -> str:
    """Generate a cache filename from file path + mtime + size."""
    try:
        mtime = os.path.getmtime(path)
    except OSError:
        mtime = 0
    raw = f"{path}|{mtime}|{size}"
    return hashlib.md5(raw.encode()).hexdigest()


class GlobalCacheIndex:
    """Cross-project index: maps cache_key → absolute path of cached PNG.

    Lives at <base_cache_dir>/content_index.json so any project can find
    thumbnails already generated by another project.
    """

    def __init__(self, base_dir: Path):
        self._path = base_dir / "content_index.json"
        self._data: dict[str, str] = {}
        if self._path.exists():
            try:
                self._data = json.loads(self._path.read_text())
            except Exception:
                self._data = {}

    def lookup(self, key: str) -> Path | None:
        """Return path to cached PNG if another project has it, else None."""
        p = self._data.get(key)
        if p:
            path = Path(p)
            if path.exists():
                return path
            # Stale entry — remove it
            del self._data[key]
        return None

    def register(self, key: str, png_path: Path):
        """Record that this key was cached at png_path."""
        self._data[key] = str(png_path)

    def save(self):
        try:
            self._path.write_text(json.dumps(self._data))
        except Exception:
            pass


# Module-level singleton; set by ThumbCache after base_dir is known
_global_index: GlobalCacheIndex | None = None


class DiskCache:
    """Simple disk-based thumbnail cache. Stores PNGs keyed by path+mtime+size."""

    def __init__(self, cache_dir: str = None):
        if cache_dir:
            self._dir = Path(cache_dir)
        else:
            self._dir = Path.home() / ".doxyedit" / "thumbcache"
        self._dir.mkdir(parents=True, exist_ok=True)
        # Load dims index
        self._index_path = self._dir / "index.json"
        self._index: dict = {}
        if self._index_path.exists():
            try:
                self._index = json.loads(self._index_path.read_text())
            except Exception:
                self._index = {}

    def get(self, path: str, size: int) -> tuple[QPixmap, int, int] | None:
        """Try to load a cached thumbnail. Returns (pixmap, orig_w, orig_h) or None."""
        key = _cache_key(path, size)
        # Try both extensions so switching modes doesn't break existing caches
        for ext in (_FAST_EXT, _STD_EXT):
            cached_file = self._dir / f"{key}{ext}"
            if cached_file.exists():
                pm = QPixmap(str(cached_file))
                if not pm.isNull():
                    dims = self._index.get(key, {})
                    return pm, dims.get("w", 0), dims.get("h", 0)
        # Check cross-project global index
        if _global_index:
            other = _global_index.lookup(key)
            if other:
                pm = QPixmap(str(other))
                if not pm.isNull():
                    dims = self._index.get(key, {})
                    return pm, dims.get("w", 0), dims.get("h", 0)
        return None

    def put(self, path: str, size: int, pixmap: QPixmap, orig_w: int, orig_h: int):
        """Save a thumbnail to disk cache."""
        fmt, ext = _cache_fmt()
        key = _cache_key(path, size)
        cached_file = self._dir / f"{key}{ext}"
        pixmap.save(str(cached_file), fmt)
        self._index[key] = {"w": orig_w, "h": orig_h}
        if _global_index:
            _global_index.register(key, cached_file)

    def save_index(self):
        """Flush the dims index to disk."""
        try:
            self._index_path.write_text(json.dumps(self._index))
        except Exception:
            pass


class ThumbWorker(QThread):
    """Generates thumbnails in a background thread."""
    thumb_ready = Signal(str, QPixmap, int, int, int)
    visual_tags_ready = Signal(str, list)

    def __init__(self, disk_cache: DiskCache, parent=None):
        super().__init__(parent)
        self._disk_cache = disk_cache
        self._queue: deque[tuple[str, str, int]] = deque()
        self._mutex = QMutex()
        self._stop = False
        self._save_counter = 0
        self._force_regen: set[str] = set()  # asset IDs that must bypass disk cache

    def enqueue(self, asset_id: str, path: str, size: int = THUMB_SIZE):
        with QMutexLocker(self._mutex):
            self._queue = deque((a, p, s) for a, p, s in self._queue if a != asset_id)
            self._queue.append((asset_id, path, size))

    def enqueue_batch(self, items: list[tuple[str, str, int]], force: bool = False):
        with QMutexLocker(self._mutex):
            existing = {}
            for aid, path, size in self._queue:
                existing[aid] = (path, size)
            for aid, path, size in items:
                existing[aid] = (path, size)
                if force:
                    self._force_regen.add(aid)
            self._queue = deque((aid, p, s) for aid, (p, s) in existing.items())

    def reprioritize(self, priority_ids: set):
        """Move items whose asset_id is in priority_ids to the front of the queue."""
        with QMutexLocker(self._mutex):
            front = deque(item for item in self._queue if item[0] in priority_ids)
            rest  = deque(item for item in self._queue if item[0] not in priority_ids)
            self._queue = front + rest

    def clear_queue(self):
        with QMutexLocker(self._mutex):
            self._queue.clear()

    def stop(self):
        self._stop = True

    def run(self):
        while not self._stop:
            item = None
            with QMutexLocker(self._mutex):
                if self._queue:
                    item = self._queue.popleft()

            if item is None:
                self.msleep(50)
                continue

            asset_id, path, target_size = item

            # Try disk cache (skip if force-regen requested for this asset)
            force = asset_id in self._force_regen
            if force:
                self._force_regen.discard(asset_id)
            cached = None if force else self._disk_cache.get(path, target_size)
            if cached:
                pm, w, h = cached
                self.thumb_ready.emit(asset_id, pm, w, h, target_size)
                continue

            # Generate from source
            try:
                from PIL import Image as PILImage
                img, orig_w, orig_h = open_for_thumb(path, target_size)

                # Compute visual tags before thumbnailing
                try:
                    from doxyedit.autotag import compute_visual_tags
                    vtags = compute_visual_tags(img)
                    if vtags:
                        self.visual_tags_ready.emit(asset_id, vtags)
                except Exception:
                    pass

                img.thumbnail((target_size, target_size), PILImage.LANCZOS)
                pm = pil_to_qpixmap(img)
                img.close()

                # Save to disk cache
                if not pm.isNull():
                    self._disk_cache.put(path, target_size, pm, orig_w, orig_h)
                    self._save_counter += 1
                    if self._save_counter % 20 == 0:
                        self._disk_cache.save_index()
                        if _global_index:
                            _global_index.save()

                self.thumb_ready.emit(asset_id, pm, orig_w, orig_h, target_size)
            except Exception:
                self.thumb_ready.emit(asset_id, QPixmap(), 0, 0, target_size)

        # Save index on shutdown
        self._disk_cache.save_index()


_LRU_MAX = 600  # max pixmaps kept in memory (~30 MB at 160px thumbs)


def _safe_name(project_name: str) -> str:
    """Sanitize a project name for use as a directory name."""
    import re
    name = re.sub(r'[<>:"/\\|?*\x00-\x1f]', '_', project_name).strip('. ')
    return name or "default"


def _migrate_flat_cache(base_dir: Path):
    """Move any loose .png / index.json files in base_dir into a 'default' subfolder."""
    loose_pngs = list(base_dir.glob("*.png"))
    loose_idx = base_dir / "index.json"
    if not loose_pngs and not loose_idx.exists():
        return
    dest = base_dir / "default"
    dest.mkdir(exist_ok=True)
    for f in loose_pngs:
        f.rename(dest / f.name)
    if loose_idx.exists():
        loose_idx.rename(dest / "index.json")


class ThumbCache:
    """Manages memory + disk cache of thumbnails and a background worker."""

    def __init__(self):
        self._pixmaps: OrderedDict[str, QPixmap] = OrderedDict()
        self._gen_sizes: dict[str, int] = {}
        self._dims: dict[str, tuple[int, int]] = {}
        from PySide6.QtCore import QSettings
        self._base_cache_dir: Path | None = (
            Path(QSettings("DoxyEdit", "DoxyEdit").value("cache_dir"))
            if QSettings("DoxyEdit", "DoxyEdit").value("cache_dir") else None
        )
        if self._base_cache_dir is None:
            self._base_cache_dir = Path.home() / ".doxyedit" / "thumbcache"
        self._base_cache_dir.mkdir(parents=True, exist_ok=True)
        _migrate_flat_cache(self._base_cache_dir)
        global _global_index
        _global_index = GlobalCacheIndex(self._base_cache_dir)
        self._disk_cache = DiskCache(cache_dir=str(self._base_cache_dir / "default"))
        self._worker = ThumbWorker(self._disk_cache)
        self._worker.start()

    def set_project(self, project_name: str):
        """Switch disk cache to a per-project subfolder. Clears in-memory cache."""
        subfolder = self._base_cache_dir / _safe_name(project_name)
        subfolder.mkdir(parents=True, exist_ok=True)
        # Drain the worker queue before swapping disk cache
        self._worker.clear_queue()
        self._disk_cache.save_index()
        new_disk = DiskCache(cache_dir=str(subfolder))
        self._worker._disk_cache = new_disk
        self._disk_cache = new_disk
        # Clear in-memory cache so stale thumbnails from the old project don't show
        self._pixmaps.clear()
        self._gen_sizes.clear()
        self._dims.clear()

    def get(self, asset_id: str) -> QPixmap | None:
        return self._pixmaps.get(asset_id)

    def get_dims(self, asset_id: str) -> tuple[int, int] | None:
        return self._dims.get(asset_id)

    def invalidate(self, asset_id: str):
        """Remove cached pixmap so the next request regenerates it."""
        self._pixmaps.pop(asset_id, None)
        self._gen_sizes.pop(asset_id, None)
        self._dims.pop(asset_id, None)

    def request(self, asset_id: str, path: str, size: int = THUMB_SIZE):
        if self._gen_sizes.get(asset_id, 0) >= size:
            return
        self._worker.enqueue(asset_id, path, size)

    def request_batch(self, items: list[tuple[str, str]], size: int = THUMB_SIZE,
                      force: bool = False):
        needed = [(aid, path, size) for aid, path in items
                  if force or self._gen_sizes.get(aid, 0) < size]
        if needed:
            if force:
                # Force-regen: invalidate memory cache entries too
                for aid, _, _ in needed:
                    self._pixmaps.pop(aid, None)
                    self._gen_sizes.pop(aid, None)
                self._worker.enqueue_batch(needed, force=True)
            else:
                fresh    = [(a, p, s) for a, p, s in needed if a not in self._gen_sizes]
                upgrades = [(a, p, s) for a, p, s in needed if a in self._gen_sizes]
                self._worker.enqueue_batch(fresh + upgrades)

    def on_ready(self, asset_id: str, pixmap: QPixmap, w: int, h: int, gen_size: int):
        # Move to end (most-recently-used)
        self._pixmaps[asset_id] = pixmap
        self._pixmaps.move_to_end(asset_id)
        self._gen_sizes[asset_id] = gen_size
        if w and h:
            self._dims[asset_id] = (w, h)
        # Evict oldest entries if over limit
        while len(self._pixmaps) > _LRU_MAX:
            evicted = next(iter(self._pixmaps))
            del self._pixmaps[evicted]
            self._gen_sizes.pop(evicted, None)
            self._dims.pop(evicted, None)

    def clear_queue(self):
        """Stop all pending thumbnail generation without clearing the memory cache."""
        self._worker.clear_queue()

    def reprioritize(self, priority_ids: set):
        """Move the given asset IDs to the front of the generation queue."""
        self._worker.reprioritize(priority_ids)

    def clear(self):
        self._worker.clear_queue()
        self._pixmaps.clear()
        self._gen_sizes.clear()
        self._dims.clear()

    def connect_ready(self, callback):
        self._worker.thumb_ready.connect(callback)

    def connect_visual_tags(self, callback):
        self._worker.visual_tags_ready.connect(callback)

    def shutdown(self):
        self._worker.stop()
        self._worker.wait(3000)
        self._disk_cache.save_index()
        if _global_index:
            _global_index.save()
