"""Golden fixture round-trip contract. tests/fixtures/
golden_full.doxyproj.json (generated by scripts/make_golden_fixture.py)
populates every schema section; these tests pin that
(1) load -> save -> load is lossless once save normalization has run
    (generation-2 dict == generation-3 dict),
(2) unknown/future keys never crash the loader and known data stays
    intact (top-level and typed sub-object unknowns are DROPPED on the
    next save - that is the actual contract, not preservation),
(3) the fixture stays in lockstep with Project.build_save_dict so any
    schema addition forces a fixture regeneration.
Shared-identity merge (~/.doxyedit/identities.json) is patched out so
the dev machine's shared store can't leak into assertions."""
from __future__ import annotations

import json
import sys
import tempfile
import unittest
from pathlib import Path
from unittest.mock import patch

REPO_ROOT = Path(__file__).resolve().parent.parent
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

GOLDEN = REPO_ROOT / "tests" / "fixtures" / "golden_full.doxyproj.json"

# Every section the fixture must populate with at least one meaningful
# entry. local_mode (False by design) and _comment (informational) are
# deliberately absent.
POPULATED_KEYS = (
    "name", "notes", "sub_notes", "platforms", "tag_definitions",
    "tag_aliases", "custom_tags", "custom_shortcuts", "hidden_tags",
    "eye_hidden_tags", "sort_mode", "tray_items", "accent_color",
    "theme_id", "checklist", "excluded_paths", "import_sources",
    "folder_presets", "filter_presets", "posts", "identity",
    "oneup_config", "default_overlays", "release_templates",
    "identities", "blackout_periods", "campaigns", "subreddits",
    "assets",
)


def _load(path):
    """Project.load with the shared-identity store neutralized."""
    from doxyedit.models import Project
    with patch("doxyedit.shared_identities.load_shared",
               return_value={}):
        return Project.load(str(path))


def _raw():
    return json.loads(GOLDEN.read_text(encoding="utf-8"))


class TestGoldenRoundTrip(unittest.TestCase):
    def test_gen2_equals_gen3(self):
        """load golden -> save -> load again. The two post-load save
        dicts must be deeply equal: after one save has normalized the
        data (alias resolution, notes migration, sorted excluded
        paths), a second pass must change nothing."""
        proj2 = _load(GOLDEN)
        with tempfile.TemporaryDirectory() as td:
            gen2_path = Path(td) / "gen2.doxyproj.json"
            proj2.save(str(gen2_path))
            proj3 = _load(gen2_path)
            d2 = proj2.build_save_dict(str(gen2_path))
            d3 = proj3.build_save_dict(str(gen2_path))
            # Every top-level key survives the round trip.
            self.assertEqual(sorted(d2.keys()), sorted(d3.keys()))
            # Per-key compare first for a readable diff on failure.
            for key in d2:
                self.assertEqual(
                    d2[key], d3[key],
                    f"round-trip mismatch in top-level key {key!r}")
            self.assertEqual(d2, d3)

    def test_load_migrations_applied(self):
        """The fixture deliberately carries an aliased tag and CLI
        dimension notes; load must normalize both."""
        proj = _load(GOLDEN)
        b = proj.get_asset("piece_b_1")
        self.assertIsNotNone(b)
        # old_golden resolved to golden via tag_aliases.
        self.assertIn("golden", b.tags)
        self.assertNotIn("old_golden", b.tags)
        # "800x600 ..." notes migrated into specs.cli_info.
        self.assertEqual(b.notes, "")
        self.assertEqual(b.specs.get("cli_info"), "800x600 cli export")

    def test_variant_exports_and_guides_are_lossy(self):
        """Documented actual behavior: both fields are written to the
        file but Project.load never reads them back."""
        raw = _raw()
        fx = next(a for a in raw["assets"] if a["id"] == "piece_a_0")
        self.assertTrue(fx["variant_exports"])
        self.assertTrue(fx["guides"])
        proj = _load(GOLDEN)
        a = proj.get_asset("piece_a_0")
        self.assertEqual(a.variant_exports, {})
        self.assertEqual(a.guides, [])


class TestForwardCompat(unittest.TestCase):
    def test_unknown_keys_do_not_crash_load(self):
        raw = _raw()
        raw["unknown_future_section"] = {"anything": [1, 2, 3]}
        raw["assets"][0]["future_asset_field"] = "surprise"
        raw["assets"][0]["crops"][0]["future_crop_field"] = 42
        raw["assets"][0]["specs"]["future_spec"] = "kept"
        raw["posts"][0]["future_post_field"] = {"nested": True}
        with tempfile.TemporaryDirectory() as td:
            p = Path(td) / "future.doxyproj.json"
            p.write_text(json.dumps(raw, ensure_ascii=False),
                         encoding="utf-8")
            proj = _load(p)

            # Known data intact.
            self.assertEqual(proj.name, raw["name"])
            a = proj.get_asset(raw["assets"][0]["id"])
            self.assertIsNotNone(a)
            self.assertEqual(a.tags, raw["assets"][0]["tags"])
            self.assertEqual(len(a.crops), len(raw["assets"][0]["crops"]))
            self.assertEqual(len(proj.posts), len(raw["posts"]))
            post = proj.get_post(raw["posts"][0]["id"])
            self.assertEqual(post.caption_default,
                             raw["posts"][0]["caption_default"])
            self.assertEqual(post.posting_log,
                             raw["posts"][0]["posting_log"])

            # Actual contract: unknown keys at top level and in typed
            # sub-objects are silently dropped on the next save...
            d = proj.build_save_dict(str(p))
            self.assertNotIn("unknown_future_section", d)
            self.assertNotIn("future_asset_field", d["assets"][0])
            self.assertNotIn("future_crop_field",
                             d["assets"][0]["crops"][0])
            self.assertNotIn("future_post_field", d["posts"][0])
            # ...but raw passthrough dicts (specs etc.) DO preserve
            # unknown keys.
            self.assertEqual(d["assets"][0]["specs"].get("future_spec"),
                             "kept")


class TestFixtureGuard(unittest.TestCase):
    def test_every_save_key_present_in_golden(self):
        """Any new key in build_save_dict must show up in the checked-in
        fixture - schema additions force a regeneration + review."""
        from doxyedit.models import Project
        save_keys = set(Project().build_save_dict("x.doxy").keys())
        fixture_keys = set(_raw().keys())
        self.assertEqual(
            save_keys, fixture_keys,
            "top-level schema keys drifted from the golden fixture - "
            "run 'py scripts/make_golden_fixture.py' and check in the "
            "regenerated tests/fixtures/golden_full.doxyproj.json")

    def test_golden_sections_populated(self):
        raw = _raw()
        for key in POPULATED_KEYS:
            self.assertTrue(
                raw.get(key),
                f"golden fixture section {key!r} is empty - the fixture "
                "must populate every schema section")

    def test_fixture_is_binary_safe_json(self):
        """ensure_ascii=False contract: non-ASCII characters are stored
        raw, not as \\uXXXX escapes."""
        text = GOLDEN.read_text(encoding="utf-8")
        self.assertIn("夢", text)          # raw yume kanji present
        self.assertNotIn("\\u5922", text)      # never escaped


if __name__ == "__main__":
    unittest.main()
